[workspace]
members = [
  "node",
  "runtime",
  "pallets/cairo",
  "pallets/starknet",
  "pallets/randomness",
  "primitives/starknet",
]
[profile.release]
panic = "unwind"

[workspace.package]
authors = ["Abdelhamid Bakhta <@abdelhamidbakhta>"]
edition = "2021"
repository = "https://github.com/keep-starknet-strange/kaioshin/"


[workspace.dependencies]
# Substrate Frame
frame-support = { default-features = false, git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
frame-benchmarking = { default-features = false, git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
frame-system = { default-features = false, git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }

# Substrate Primitives
sp-core = { default-features = false, git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sp-std = { default-features = false, git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sp-io = { default-features = false, git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }
sp-runtime = { default-features = false, git = "https://github.com/keep-starknet-strange/substrate.git", branch = "kaioshin-dev" }

# Substrate Frame pallet

# Kaioshin pallets
pallet-cairo = { version = "0.1.0-dev", path = "pallets/cairo", default-features = false }
pallet-starknet = { version = "0.1.0-dev", path = "pallets/starknet", default-features = false }
pallet-kaioshin-randomness = { version = "0.1.0-dev", path = "pallets/randomness", default-features = false }

# Kaioshin primtitives
kp-starknet = { version = "0.1.0-dev", path = "primitives/starknet", default-features = false }

# Starknet dependencies
# Cairo Virtual Machine
# TODO: wait for no-std support on official repo
cairo-vm = { git = "https://github.com/open-dust/cairo-rs", branch = "wasm32-support", default-features = false, features = [
  "alloc",
] }
starknet-crypto = { git = "https://github.com/tdelabro/starknet-rs.git", branch = "feature/manual-no-std-bigdecimal", default-features = false }
starknet-ff = { git = "https://github.com/tdelabro/starknet-rs.git", branch = "feature/manual-no-std-bigdecimal", default-features = false }
poseidon_hash = { default-features = false, package = "poseidon", git = "https://github.com/EvolveArt/poseidon-rs", branch = "feature/no-std-refractor", features = [
  "alloc",
] }

# Other third party dependencies
lazy_static = { version = "1.4.0", default-features = false }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
  "derive",
] }
scale-info = { version = "2.1.1", default-features = false, features = [
  "derive",
] }
log = "0.4.17"
hex = { version = "0.4.3", default-features = false }
safe-mix = { version = "1.0", default-features = false }
