global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "substrate-nodes"
    static_configs:
      - targets: ["127.0.0.1:9615"]
        labels:
          network: dev
      - targets: ["127.0.0.1:9715"]
        labels:
          network: dev
